"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['wibBot.py']
DATA_FILES = ['logo.icns', 'logo.png', 'wlivePurpose.py']
OPTIONS = {
    'iconfile':'logo.icns',
    'plist':{'CFBundleShortVersionString':'0.1.0',}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
